USB_VID = 0x32AC
USB_PID = 0x0013
USB_PRODUCT = "Ledmatrix Laptop 16 Keyboard (CircuitPython)"
USB_MANUFACTURER = "Framework Computer Inc"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

QSPI_FLASH_FILESYSTEM = 1
#EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = "W25Q80DV"

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_IS31FL3731
