USB_VID = 0x32AC
USB_PID = 0x0013
USB_PRODUCT = "Ledmatrix Laptop 16 Keyboard (CircuitPython)"
USB_MANUFACTURER = "Framework Computer Inc"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

QSPI_FLASH_FILESYSTEM = 1
#EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = "W25Q80DV"

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_IS31FL3731

# Flash is only 1M, reduce firmware to half, so there's space for the CIRCUITPY drive
# Must be accompanied by a linker script change
CFLAGS += -DCIRCUITPY_FIRMWARE_SIZE='(512 * 1024)'

#CIRCUITPY_DISPLAULAB_HAS_USER_MODULEYIO = 1
CIRCUITPY_TOUCHIO = 1
#CIRCUITPY_PWMIO = 1

# Boards hav limited IO, only
# - IS31FL3741/IS31FL3731 LED matrix
# - USB 2.0
# - PWM backlight
# - Capslock LED
#CIRCUITPY_ANALOGIO = 0 # TODO: Might want this
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOBUSIO_I2SOUT = 0
CIRCUITPY_AUDIOCORE = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_AUDIOPWMIO = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY_BLEIO_HCI=0
CIRCUITPY_BLEIO=0
CIRCUITPY_PS2IO = 0

CIRCUITPY_MSGPACK = 0
CIRCUITPY_RTC = 1
CIRCUITPY_FRAMEBUFFERIO = 0 # TODO: Might want this
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_TERMINALIO = 0
CIRCUITPY_VECTORIO = 0
CIRCUITPY_ULAB = 0 # Like numpy for circuitpython
CIRCUITPY_USB_MIDI=0

#CIRCUITPY_BITBANG_APA102 = 0
#CIRCUITPY_BITBANGIO = 1 # Need for I2C
#CIRCUITPY_BITMAPTOOLS = 0
#CIRCUITPY_BUSDEVICE = 1 # TODO: What's this?
#CIRCUITPY_FREQUENCYIO = 0
#CIRCUITPY_I2CTARGET = 1
#CIRCUITPY_NEOPIXEL_WRITE = 0
#CIRCUITPY_NVM = 0
#CIRCUITPY_PIXELBUF = 0
#CIRCUITPY_PULSEIO = 0
#CIRCUITPY_RGBMATRIX = 0
#CIRCUITPY_SAMD = 0
#CIRCUITPY_USB_HID = 0 # TODO: Might want this
#CIRCUITPY_USB_VENDOR = 0 # TODO: Might want this
