CIRCUITPY_CREATOR_ID = 0x10111011
CIRCUITPY_CREATION_ID = 0x00C60008

IDF_TARGET = esp32c6

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

CIRCUITPY_AUDIOBUSIO = 1
CIRCUITPY_AUDIOI2SIN = 1
# Fit the 2MB firmware partition
CIRCUITPY_ULAB_OPTIMIZE_SIZE = 1
