
INTERNAL_FLASH_FILESYSTEM = 0
QSPI_FLASH_FILESYSTEM = 0
SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = MX25R3235F

MCU_SERIES = MG24
MCU_VARIANT = EFR32MG24B310F1536IM48

CIRCUITPY_USB = 0
CIRCUITPY_BUSIO = 1
CIRCUITPY_BLEIO = 1
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_FRAMEBUFFERIO = 1
CIRCUITPY_PULSEIO = 0
CIRCUITPY_PWMIO = 1
CIRCUITPY_DISPLAYIO = 1
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_ANALOGIO = 1

CIRCUITPY_CREATOR_ID =  0x19960000
CIRCUITPY_CREATION_ID = 0x00242601
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_BLE
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_Register
