
BOARD_BRD = brd2704a
INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = MG24
MCU_VARIANT = MGM240PB32VNA

CIRCUITPY_CREATOR_ID =  0x19960000
CIRCUITPY_CREATION_ID = 0x00242704
CIRCUITPY_SDCARDIO = 1

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_BLE
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_Register
