USB_VID = 0x1a86
USB_PID = 0x5d37
USB_PRODUCT = "Waveshare ESP32S3 LCD 1.28"
USB_MANUFACTURER = "Waveshare"

IDF_TARGET = esp32s3

# This flash lives outside the module.
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 16MB

CIRCUITPY_ESP_PSRAM_SIZE = 2MB
CIRCUITPY_ESP_PSRAM_MODE = qio
CIRCUITPY_ESP_PSRAM_FREQ = 80m

INTERNAL_FLASH_FILESYSTEM = 0
QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = W25Q128JVxQ

CIRCUITPY_ESPCAMERA = 0
