USB_VID = 0x1366
USB_PID = 0x0105
USB_PRODUCT = "Sparkfun Thing Plus MGM240P"
USB_MANUFACTURER = "SiLabs"

INTERNAL_FLASH_FILESYSTEM = 1
QSPI_FLASH_FILESYSTEM = 0
SPI_FLASH_FILESYSTEM = 0

MCU_SERIES = MG24
MCU_VARIANT = MGM240PB32VNA

CIRCUITPY_USB = 0
CIRCUITPY_BUSIO = 1
CIRCUITPY_BLEIO = 1
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_FRAMEBUFFERIO = 1
CIRCUITPY_PULSEIO = 0
CIRCUITPY_PWMIO = 1
CIRCUITPY_DISPLAYIO = 1
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_SDCARDIO = 1
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_ANALOGIO = 1

CIRCUITPY_CREATOR_ID = 0x02FF
CIRCUITPY_CREATION_ID = 0x02FF
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_BLE
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_Register
