#USB_VID = 0x15BA
#USB_PID = 0x0054
CIRCUITPY_CREATOR_ID = 0x000c15BA
CIRCUITPY_CREATION_ID = 0x00000054
USB_PRODUCT = "RP2350pc"
USB_MANUFACTURER = "Olimex"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ, P25Q16H"

CIRCUITPY_USB_DEVICE=0
CIRCUITPY_USB_IDENTIFICATION = 0
CIRCUITPY_USB_VIDEO=0
#CIRCUITPY_USB_MIDI=0
#CIRCUITPY_USB_CDC = 0
#CIRCUITPY_USB_HID = 0
#CIRCUITPY_USB_MSC = 0

CIRCUITPY_USB_HOST=1
#CIRCUITPY_TINYUSB_HOST=1
#CIRCUITPY_USB_HOST_INSTANCE = 0

CIRCUITPY_BUILD_EXTENSIONS = uf2
UF2_BOOTLOADER = 1
#OPTIMIZATION_FLAGS = -Os
