USB_VID = 0x303A
USB_PID = 0x8249
USB_PRODUCT = "ESP32-B"
USB_MANUFACTURER = "OHARARP LLC"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_SIZE = 16MB
CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_NEOPIXEL_WRITE = 1
