#include "shared-bindings/board/__init__.h"

STATIC const mp_rom_map_elem_t board_module_globals_table[] = {
    CIRCUITPYTHON_BOARD_DICT_STANDARD_ITEMS

    // Left Side

    // D0/SDA0/TX0/RX0/PWM0A
    { MP_ROM_QSTR(MP_QSTR_D0), MP_ROM_PTR(&pin_GPIO0) },
    // D1/SCL0/RX0/CS0/PWM0B
    { MP_ROM_QSTR(MP_QSTR_D1), MP_ROM_PTR(&pin_GPIO1) },
    // GND/(D10/SDA1/CTS0/SCK0/PWM5A) (Jumper required)
    { MP_ROM_QSTR(MP_QSTR_D10), MP_ROM_PTR(&pin_GPIO10) },
    // GND/(D11/SCL1/RTS0/TX0/PWM5B) (Jumper Required)
    { MP_ROM_QSTR(MP_QSTR_D11), MP_ROM_PTR(&pin_GPIO11) },
    // D2/SDA1/CTS0/SCK0/PWM1A
    { MP_ROM_QSTR(MP_QSTR_D2), MP_ROM_PTR(&pin_GPIO2) },
    // D3/SCL1/RTS0/TX0/PWM1B
    { MP_ROM_QSTR(MP_QSTR_D3), MP_ROM_PTR(&pin_GPIO3) },
    // D4/SDA0/TX1/RX0/PWM2A
    { MP_ROM_QSTR(MP_QSTR_D4), MP_ROM_PTR(&pin_GPIO4) },
    // D5/SCL0/RX1/CS0/PWM2B
    { MP_ROM_QSTR(MP_QSTR_D5), MP_ROM_PTR(&pin_GPIO5) },
    // D6/SDA1/CTS1/SCK0/PWM3A
    { MP_ROM_QSTR(MP_QSTR_D6), MP_ROM_PTR(&pin_GPIO6) },
    // D7/SCL1/RTS1/TX0/PWM3B
    { MP_ROM_QSTR(MP_QSTR_D7), MP_ROM_PTR(&pin_GPIO7) },
    // D8/SDA0/TX1/RX0/PWM4A
    { MP_ROM_QSTR(MP_QSTR_D8), MP_ROM_PTR(&pin_GPIO8) },
    // D9/SCL0/RX1/CS1/4B
    { MP_ROM_QSTR(MP_QSTR_D9), MP_ROM_PTR(&pin_GPIO9) },

    // Right Side

    // D29/A3/SCL0/RX0/CS1/PWM6B
    { MP_ROM_QSTR(MP_QSTR_A3), MP_ROM_PTR(&pin_GPIO29) },
    { MP_ROM_QSTR(MP_QSTR_D29), MP_ROM_PTR(&pin_GPIO29) },
    { MP_ROM_QSTR(MP_QSTR_D29_A3), MP_ROM_PTR(&pin_GPIO29) },
    // D28/A2/SDA0/TX0/RX1/PWM6A
    { MP_ROM_QSTR(MP_QSTR_A2), MP_ROM_PTR(&pin_GPIO28) },
    { MP_ROM_QSTR(MP_QSTR_D28), MP_ROM_PTR(&pin_GPIO28) },
    { MP_ROM_QSTR(MP_QSTR_D28_A2), MP_ROM_PTR(&pin_GPIO28) },
    // D27/A1/SCL1/RTS1/TX1/PWM5B
    { MP_ROM_QSTR(MP_QSTR_A1), MP_ROM_PTR(&pin_GPIO27) },
    { MP_ROM_QSTR(MP_QSTR_D27), MP_ROM_PTR(&pin_GPIO27) },
    { MP_ROM_QSTR(MP_QSTR_D27_A1), MP_ROM_PTR(&pin_GPIO27) },
    // D26/A0/SDA1/CTS1/SCK1/PWM5A
    { MP_ROM_QSTR(MP_QSTR_A0), MP_ROM_PTR(&pin_GPIO26) },
    { MP_ROM_QSTR(MP_QSTR_D26), MP_ROM_PTR(&pin_GPIO26) },
    { MP_ROM_QSTR(MP_QSTR_D26_A0), MP_ROM_PTR(&pin_GPIO26) },
    // D22/SDA1/TX1/RX0/PWM3A
    { MP_ROM_QSTR(MP_QSTR_D22), MP_ROM_PTR(&pin_GPIO22) },
    // D20/SDA0/TX1/RX0/PWM2A
    { MP_ROM_QSTR(MP_QSTR_D20), MP_ROM_PTR(&pin_GPIO20) },
    // D23/SCL1/RTS1/TX0/PWM3B
    { MP_ROM_QSTR(MP_QSTR_D23), MP_ROM_PTR(&pin_GPIO23) },
    // D21/SCL0/RX1/CS0/PWM2B
    { MP_ROM_QSTR(MP_QSTR_D21), MP_ROM_PTR(&pin_GPIO21) },

    // Bottom Edge

    // D12/SDA0/TX0/RX1/PWM6A
    { MP_ROM_QSTR(MP_QSTR_D12), MP_ROM_PTR(&pin_GPIO12) },
    // D13/SCL0/RX0/CS1/PWM6B
    { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_GPIO13) },
    // D14/SDA1/CTS0/SCK1/PWM7A
    { MP_ROM_QSTR(MP_QSTR_D14), MP_ROM_PTR(&pin_GPIO14) },
    // D15/SCL1/RTS0/TX1/PWM7B
    { MP_ROM_QSTR(MP_QSTR_D15), MP_ROM_PTR(&pin_GPIO15) },
    // D16/SDA0/TX0/RX0/PWM0A
    { MP_ROM_QSTR(MP_QSTR_D16), MP_ROM_PTR(&pin_GPIO16) },

    // Misc

    // (No internally wired pins or non-pin ports)
};
MP_DEFINE_CONST_DICT(board_module_globals, board_module_globals_table);
