USB_VID = 0x1209
USB_PID = 0xBAB0
USB_PRODUCT = "Bast WiFi"
USB_MANUFACTURER = "ElectronicCats"

IDF_TARGET = esp32s2

CIRCUITPY_NEOPIXEL_WRITE = 0

CIRCUITPY_ESP_FLASH_SIZE = 4MB
CIRCUITPY_ESP32_CAMERA = 0
