USB_VID = 0x1209
USB_PID = 0x4252
USB_PRODUCT = "RAPID-0"
USB_MANUFACTURER = "Bruin Spacecraft Group"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = H7
MCU_VARIANT = STM32H743xx
MCU_PACKAGE = LQFP100_x7

LD_COMMON = boards/common_tcm.ld
LD_FILE = boards/STM32H743_bigfs.ld

CIRCUITPY_BOARD = 0

CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_KEYPAD = 0
CIRCUITPY_EPAPERDISPLAY = 0
