USB_VID = 0x1209
USB_PID = 0x0001
USB_PRODUCT = "Equinox"
USB_MANUFACTURER = "MoonYard"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"

CIRCUITPY_PICODVI = 0
CIRCUITPY_USB_HOST = 0
