# SPDX-FileCopyrightText: 2014 MicroPython & CircuitPython contributors (https://github.com/adafruit/circuitpython/graphs/contributors)
#
# SPDX-License-Identifier: MIT

name: Update CircuitPython.org

on:
  release:
    types: [published, rerequested]

jobs:
  website:
    runs-on: ubuntu-22.04
    steps:
    - name: Dump GitHub context
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Set up repository
      uses: actions/checkout@v3
      with:
        submodules: false
        fetch-depth: 1
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: CircuitPython dependencies
      run: |
        python tools/ci_fetch_deps.py ${{ github.job }}
        echo "::group::Fetch history and tags"
        git fetch --no-recurse-submodules --shallow-since="2021-07-01" --tags https://github.com/adafruit/circuitpython HEAD
        git fetch --no-recurse-submodules --shallow-since="2021-07-01" origin $GITHUB_SHA
        git repack -d
        echo "::endgroup::"
    - name: CircuitPython version
      run: |
        CP_VERSION=$(tools/describe)
        echo "$CP_VERSION"
        echo "CP_VERSION=$CP_VERSION" >> $GITHUB_ENV
    - name: Install dependencies
      run: pip install -r requirements-dev.txt
    - name: Versions
      run: |
        gcc --version
        python3 --version
    - name: Website
      run: python3 build_board_info.py
      working-directory: tools
      env:
        RELEASE_TAG: ${{ github.event.release.tag_name }}
        ADABOT_GITHUB_ACCESS_TOKEN: ${{ secrets.ADABOT_GITHUB_ACCESS_TOKEN }}
