name: Run tests

on:
  workflow_call:
    inputs:
      cp-version:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        test: [all, mpy, native, native_mpy]
    env:
      CP_VERSION: ${{ inputs.cp-version }}
      MICROPY_CPYTHON3: python3.8
      MICROPY_MICROPYTHON: ../ports/posix/circuitpython
      TEST_all:
      TEST_mpy: --via-mpy -d basics float micropython
      TEST_native: --emit native
      TEST_native_mpy: --via-mpy --emit native -d basics float micropython
    steps:
    - name: Set up repository
      uses: actions/checkout@v4
      with:
        submodules: false
        show-progress: false
        fetch-depth: 1
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Set up submodules
      uses: ./.github/actions/deps/submodules
      with:
        target: tests
    - name: Set up external
      if: matrix.test == 'all'
      uses: ./.github/actions/deps/external
    - name: Set up mpy-cross
      uses: ./.github/actions/mpy_cross
      with:
        cp-version: ${{ inputs.cp-version }}
    - name: Build & test POSIX port
      run: make -C ports/posix -j$(nproc) vtest
